### ISSUE TITLE
How to disassemble the touch sensor from the black plastic board？

### ISSUE THREAD

**Issue by HereXianggeGe** [jbamuro/waccamole#7]
I can’t directly disassemble the white board. I need to fully disassemble the soft touch pcb.
![IMG_6112](https://github.com/jbamuro/waccamole/assets/63825505/e5874f67-b24e-45d7-bcab-b1bbeac3d3b9)
![IMG_6113](https://github.com/jbamuro/waccamole/assets/63825505/6c472ca6-5e11-406a-91f2-6a4759db993c)
![IMG_6114](https://github.com/jbamuro/waccamole/assets/63825505/036fe73d-a369-4ce7-9cbb-f868dfd2dd78)

**Comment by AkaiiKitsune** [comment]
This is extremely hard to do, as far as I remember everything is glued down (on both sides of the soft PCB).

I had to use a hairdryer, some IPA and an excessive use of force to disassemble the one I scanned for this documentation.

You basically have to rip that shit apart without breaking anything 😅

**Comment by HereXianggeGe** [comment]
Thanks for your reply! Indeed it’s a dump structure lol.

**Comment by HereXianggeGe** [comment]
I will close this issue, thanks!
